# Textbook-derived structured quiz data
QUESTIONS=[]
def add(ch,prompt,opts,ans,why,topic,d='medium'):
    QUESTIONS.append({'id':f'C{ch}-{len(QUESTIONS)+1:03d}','chapter':ch,'prompt':prompt,'options':[str(x) for x in opts],'answer':ans,'explanation':why,'topic':topic,'difficulty':d})
def num_opts(a):
    a=float(a); step=1 if abs(a)>=10 else 0.1
    vals=[a,a+step,max(0,a-step),a+2*step]; out=[]
    for v in vals:
        s=str(int(v)) if v==int(v) else str(round(v,3))
        if s not in out: out.append(s)
    return out
def addnum(ch,prompt,a,why,topic,d='medium'):
    add(ch,prompt,num_opts(a),0,why,topic,d)
add(3,'3 hours is what fraction of a day?',['1/8','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(3,'8 hours is what fraction of a day?',['1/3','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(3,'6 months is what fraction of one year?',['1/2','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(3,'8 months is what fraction of one year?',['2/3','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(3,'40 minutes is what fraction of an hour?',['2/3','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(3,'20 minutes is what fraction of an hour?',['1/3','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(3,'50 paise is what fraction of a rupee?',['1/2','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(3,'₹2 is what fraction of ₹10?',['1/5','1/4','3/4','5/6'],0,'Convert the quantity to a fraction of the whole and simplify.','Fractions')
add(4,'Write 11.163 in expanded form.',['11 + 0.1 + 0.06 + 0.003', '11 + 0.1 + 0.06 + 0.003 + 1', '11 + 163', '0 + 11 + 0.1 + 0.06 + 0.003'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
add(4,'Write 7.809 in expanded form.',['7 + 0.8 + 0.009', '7 + 0.8 + 0.009 + 1', '7 + 809', '0 + 7 + 0.8 + 0.009'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
add(4,'Write 2.46 in expanded form.',['2 + 0.4 + 0.06', '2 + 0.4 + 0.06 + 1', '2 + 46', '0 + 2 + 0.4 + 0.06'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
add(4,'Write 1.275 in expanded form.',['1 + 0.2 + 0.07 + 0.005', '1 + 0.2 + 0.07 + 0.005 + 1', '1 + 275', '0 + 1 + 0.2 + 0.07 + 0.005'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
add(4,'Write 24.24 in expanded form.',['24 + 0.2 + 0.04', '24 + 0.2 + 0.04 + 1', '24 + 24', '0 + 24 + 0.2 + 0.04'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
add(4,'Write 7.682 in expanded form.',['7 + 0.6 + 0.08 + 0.002', '7 + 0.6 + 0.08 + 0.002 + 1', '7 + 682', '0 + 7 + 0.6 + 0.08 + 0.002'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
add(4,'Write 224.27 in expanded form.',['224 + 0.2 + 0.07', '224 + 0.2 + 0.07 + 1', '224 + 27', '0 + 224 + 0.2 + 0.07'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
add(4,'Write 123.789 in expanded form.',['123 + 0.7 + 0.08 + 0.009', '123 + 0.7 + 0.08 + 0.009 + 1', '123 + 789', '0 + 123 + 0.7 + 0.08 + 0.009'],0,'Separate the whole number, tenths, hundredths and thousandths.','Decimals')
addnum(4,'Write “Four hundredths” as a decimal.',0.04,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'Write “Twenty-two thousandths” as a decimal.',0.022,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'Write “Two and five tenths” as a decimal.',2.5,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'What is the next number: 1.02, 1.03, 1.04, …',1.05,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'What is the next number: 0.234, 0.235, 0.236, …',0.237,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'Convert 52 p into rupees.',0.52,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'Convert 45 cm into metres.',0.45,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'Convert 176 m into kilometres.',0.176,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'Convert 229 g into kilograms.',0.229,'Use the decimal relationship between the two units.','Decimals')
addnum(4,'Convert 288 ml into litres.',0.288,'Use the decimal relationship between the two units.','Decimals')
addnum(5,'Calculate: 5793 + 6725',12518,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 5789 + 6728',12517,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 32784 + 84832',117616,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 38657 − 24325',14332,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 24895 − 20044',4851,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 4594 − 3453',1141,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 40588 − 31944',8644,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 94532 − 52466',42066,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'Calculate: 46802 − 29468',17334,'Align place values and calculate carefully.','Arithmetic')
addnum(5,'A school library has 2592 English books, 4854 Hindi books and 5928 other books. How many books are there in total?',13374,'Translate the word problem into the required addition or subtraction.','Word problems','hard')
addnum(5,'A town has a population of 75492. If 40548 are males, how many are females?',34944,'Translate the word problem into the required addition or subtraction.','Word problems','hard')
addnum(5,'A shopkeeper had 2453 kg of sugar and sold 526 kg and 859 kg. How much was left?',1068,'Translate the word problem into the required addition or subtraction.','Word problems','hard')
addnum(5,'What must be added to 2571 to get 4000?',1429,'Translate the word problem into the required addition or subtraction.','Word problems','hard')
addnum(5,'Subtract the sum of 4025 and 1512 from 9669.',4132,'Translate the word problem into the required addition or subtraction.','Word problems','hard')
addnum(5,'A factory manufactured 9574 toys and sent 2595 to one market and 2659 to another. How many were left?',4320,'Translate the word problem into the required addition or subtraction.','Word problems','hard')
addnum(6,'Find the product: 46 × 1000',46000,'Multiply using place value and partial products.','Multiplication','medium')
addnum(6,'Find the product: 6 × 2000',12000,'Multiply using place value and partial products.','Multiplication','medium')
addnum(6,'Find the product: 21 × 4000',84000,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Find the product: 28 × 3000',84000,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Find the product: 17 × 5000',85000,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Find the product: 247 × 36',8892,'Multiply using place value and partial products.','Multiplication','medium')
addnum(6,'Find the product: 349 × 84',29316,'Multiply using place value and partial products.','Multiplication','medium')
addnum(6,'Find the product: 2428 × 28',67984,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Find the product: 405 × 227',91935,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Find the product: 525 × 49',25725,'Multiply using place value and partial products.','Multiplication','medium')
addnum(6,'Find the product: 636 × 54',34344,'Multiply using place value and partial products.','Multiplication','medium')
addnum(6,'Find the product: 480 × 112',53760,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Find the product: 712 × 228',162336,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Find the product: 819 × 209',171171,'Multiply using place value and partial products.','Multiplication','hard')
addnum(6,'Aman saves ₹350 per month. How much does he save in 4 years?',16800,'Identify the repeated quantity and multiply.','Word problems','hard')
addnum(6,'Sita types 68 words per minute. How many words in 2 hours 20 minutes?',9520,'Identify the repeated quantity and multiply.','Word problems','hard')
addnum(6,'A monthly fee is ₹225 per student. What is the total for 625 students?',140625,'Identify the repeated quantity and multiply.','Word problems','hard')
addnum(6,'The price of a pen is ₹120. Find the price of 150 pens.',18000,'Identify the repeated quantity and multiply.','Word problems','hard')
addnum(6,'A basket contains 228 apples. How many apples are in 325 baskets?',74100,'Identify the repeated quantity and multiply.','Word problems','hard')
addnum(6,'There are 325 buses and each bus has 59 passengers. How many passengers are there?',19175,'Identify the repeated quantity and multiply.','Word problems','hard')
add(9,'The longest chord of a circle is called:',['Diameter', 'Radius', 'Arc', 'Sector'],0,'A diameter is the longest chord.','Circle concepts')
add(9,'A line segment joining the centre of a circle to a point on the circle is called:',['Radius', 'Chord', 'Diameter', 'Arc'],0,'A radius joins the centre to the circle.','Circle concepts')
add(9,'A line segment joining two points on a circle is called:',['Chord', 'Radius', 'Sector', 'Arc'],0,'A chord has both endpoints on the circle.','Circle concepts')
add(9,'The region bounded by an arc and two radii is called a:',['Sector', 'Segment', 'Arc', 'Secant'],0,'A sector is bounded by two radii and an arc.','Circle concepts')
addnum(9,'Find the radius of a circle whose diameter is 14 cm.',7.0,'Radius = diameter ÷ 2.','Circle measurement')
addnum(9,'Find the radius of a circle whose diameter is 80 cm.',40.0,'Radius = diameter ÷ 2.','Circle measurement')
addnum(9,'Find the radius of a circle whose diameter is 24 cm.',12.0,'Radius = diameter ÷ 2.','Circle measurement')
addnum(9,'Find the radius of a circle whose diameter is 48 cm.',24.0,'Radius = diameter ÷ 2.','Circle measurement')
addnum(9,'Find the radius of a circle whose diameter is 6 cm.',3.0,'Radius = diameter ÷ 2.','Circle measurement')
addnum(9,'Find the radius of a circle whose diameter is 120 cm.',60.0,'Radius = diameter ÷ 2.','Circle measurement')
addnum(9,'Find the diameter of a circle whose radius is 6 cm.',12,'Diameter = 2 × radius.','Circle measurement')
addnum(9,'Find the diameter of a circle whose radius is 18 cm.',36,'Diameter = 2 × radius.','Circle measurement')
addnum(9,'Find the diameter of a circle whose radius is 12 cm.',24,'Diameter = 2 × radius.','Circle measurement')
add(10,'How many lines of symmetry does an equilateral triangle have?',['0', '1', '2', '3', '4'],3,'Count the lines that divide the figure into matching mirror-image halves.','Symmetry','medium')
add(10,'How many lines of symmetry does an isosceles triangle have?',['0', '1', '2', '3', '4'],1,'Count the lines that divide the figure into matching mirror-image halves.','Symmetry','medium')
add(10,'How many lines of symmetry does a scalene triangle have?',['0', '1', '2', '3', '4'],0,'Count the lines that divide the figure into matching mirror-image halves.','Symmetry','medium')
add(10,'How many lines of symmetry does a square have?',['0', '1', '2', '3', '4'],4,'Count the lines that divide the figure into matching mirror-image halves.','Symmetry','medium')
add(10,'How many lines of symmetry does a rectangle have?',['0', '1', '2', '3', '4'],2,'Count the lines that divide the figure into matching mirror-image halves.','Symmetry','hard')
add(10,'How many lines of symmetry does a rhombus have?',['0', '1', '2', '3', '4'],2,'Count the lines that divide the figure into matching mirror-image halves.','Symmetry','hard')
add(10,'Which statement best describes a line of symmetry?',['It divides a figure into two matching mirror-image halves.', 'It divides every figure into triangles.', 'It must be horizontal.', 'It must be vertical.'],0,'A line of symmetry creates two matching mirror-image halves.','Core concept')
add(10,'Which method can be used to test a proposed line of symmetry?',['Fold along the proposed line.', 'Measure one side only.', 'Count the corners.', 'Change the colour.'],0,'Folding checks whether the two halves exactly coincide.','Core concept')
add(10,'As an object goes farther away, it appears to be:',['smaller', 'bigger', 'unchanged', 'closer'],0,'Perspective makes distant objects appear smaller.','Perspective')
add(10,'The vanishing point usually lies on the:',['horizon line', 'bottom edge', 'nearest object', 'mirror line'],0,'In perspective drawings the vanishing point lies on the horizon line.','Perspective')
add(10,'How many lines of symmetry does the capital letter A have?',['0', '1', '2', '4'],1,'In standard block lettering, A has 1 line(s) of symmetry.','Letters','hard')
add(10,'How many lines of symmetry does the capital letter H have?',['0', '1', '2', '4'],2,'In standard block lettering, H has 2 line(s) of symmetry.','Letters','hard')
add(10,'How many lines of symmetry does the capital letter M have?',['0', '1', '2', '4'],1,'In standard block lettering, M has 1 line(s) of symmetry.','Letters','hard')
add(10,'How many lines of symmetry does the capital letter O have?',['0', '1', '2', '4'],2,'In standard block lettering, O has 2 line(s) of symmetry.','Letters','hard')
add(10,'How many lines of symmetry does the capital letter T have?',['0', '1', '2', '4'],1,'In standard block lettering, T has 1 line(s) of symmetry.','Letters','hard')
add(10,'How many lines of symmetry does the capital letter X have?',['0', '1', '2', '4'],2,'In standard block lettering, X has 2 line(s) of symmetry.','Letters','hard')
add(10,'How many lines of symmetry does the capital letter Y have?',['0', '1', '2', '4'],1,'In standard block lettering, Y has 1 line(s) of symmetry.','Letters','hard')
add(10,'How many lines of symmetry does the capital letter Z have?',['0', '1', '2', '4'],0,'In standard block lettering, Z has 0 line(s) of symmetry.','Letters','hard')
assert len(QUESTIONS)>=70
